### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by worldlew** [liuchq/moxueyuan#1]
C:\Users\JasonLiu\Downloads\moxueyuan-master\moxueyuan-master\src\com\liuchq\moxueyuan\MoXueYuanUtil.java:3:28
java: 程序包com.alibaba.fastjson不存在
C:\Users\JasonLiu\Downloads\moxueyuan-master\moxueyuan-master\src\com\liuchq\moxueyuan\MoXueYuanUtil.java:133:13
java: 找不到符号
  符号:   类 JSONObject
  位置: 类 com.liuchq.moxueyuan.MoXueYuanUtil
C:\Users\JasonLiu\Downloads\moxueyuan-master\moxueyuan-master\src\com\liuchq\moxueyuan\MoXueYuanUtil.java:133:38
java: 找不到符号
  符号:   类 JSONObject
  位置: 类 com.liuchq.moxueyuan.MoXueYuanUtil
C:\Users\JasonLiu\Downloads\moxueyuan-master\moxueyuan-master\src\com\liuchq\moxueyuan\MoXueYuanUtil.java:133:49
java: 找不到符号
  符号:   变量 JSONObject
  位置: 类 com.liuchq.moxueyuan.MoXueYuanUtil

**Comment by liuchq** [comment]
com.alibaba.fastjson  网上下载一个  fastjson包就行

**Comment by worldlew** [comment]
十分感谢回复，上面问题已解决。
请问这个脚本需要怎么编译呢？希望出一个使用教程
我使用idea运行的时候出现，不知如何解决
"C:\Program Files\Java\jdk1.8.0_162\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2020.3\lib\idea_rt.jar=2558:C:\Program Files\JetBrains\IntelliJ IDEA 2020.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_162\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_162\jre\lib\rt.jar;C:\moxueyuan-master\out\production\moxueyuan-master;C:\Users\JasonLiu\Downloads\fastjson-1.2.75.jar" com.liuchq.moxueyuan.StartStudy
java.io.FileNotFoundException: C:\StudyLog.txt (拒绝访问。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at com.liuchq.moxueyuan.MoXueYuanLog.setLog(MoXueYuanLog.java:23)
	at com.liuchq.moxueyuan.StartStudy.main(StartStudy.java:21)
Exception in thread "main" java.lang.NullPointerException
	at com.liuchq.moxueyuan.MoXueYuanLog.setLog(MoXueYuanLog.java:37)
	at com.liuchq.moxueyuan.StartStudy.main(StartStudy.java:21)
日志存储的地址不正确C:\StudyLog.txt

Process finished with exit code 1

**Comment by worldlew** [comment]
Studylog和Study都放在C根目录

**Comment by worldlew** [comment]
十分感谢回复，上面的问题已经解决，
请问怎么获取课程代码,token呢?我在Cookie里找到AGL_USER_ID，在网页源代码里找到EID,希望出一个使用教程

**Comment by liuchq** [comment]
> 十分感谢回复，上面的问题已经解决，
> 请问怎么获取课程代码,token呢?我在Cookie里找到AGL_USER_ID，在网页源代码里找到EID,希望出一个使用教程



![aa](https://user-images.githubusercontent.com/43339366/103163409-7cb92480-47f5-11eb-9437-5ed80b123da5.png)
你先打开一个需要你学习的课程，然后F12打开控制台，进入Network,寻找截图中的请求，就可以找到你需要的参数值。
不同的课程，修改课程ID就行

这个项目已经好几个月没用过了，不保证它还能正常刷颗^_^

**Comment by worldlew** [comment]
再次感谢解答，已经正常运行刷课，脚本原理是模拟打开多个窗口同时播放，我看到参数里会记录课程开始结束时间，这样后台会看到同一时间看完所有课程，严重与常规不符，有封号风险，感谢你的分享。

**Comment by liuchq** [comment]
> 再次感谢解答，已经正常运行刷课，脚本原理是模拟打开多个窗口同时播放，我看到参数里会记录课程开始结束时间，这样后台会看到同一时间看完所有课程，严重与常规不符，有封号风险，感谢你的分享。

按照你自己的想法可以自行修改代码运行逻辑。规避你认为的风险
